import assert from 'node:assert/strict';
import test from 'node:test';
import checker from '../emulator/assert-screens.cjs';
import * as fixture from '../fixtures.mjs';

// Actual Nano X 1.22.3 capture from the corrected public-test approval run
// injection-result-N3HBwL. Captured text only: no signature or wallet state.
const approvalScreens = [
  'Ethereum | app is ready',
  'Interaction with | Rebalance  | development',
  'Contract | 0x5fc5360D0400a0Fd | 4f2af552ADD042D71 | 6F1d168',
  'Native value (wei) | 0',
  'Spender | 0xCaf681a66D020601 | 342297493863E78C95 | 9E5cb2',
  'Approval amount | 8 USDG',
  'Network | Robinhood Chain',
  'Max fees | 0.000000000001 ETH',
  'Sign transaction',
];
const check = (events, fixtureName = 'approval', signerAddress) =>
  checker.assertScreens({ events, fixture, fixtureName, signerAddress });

// Deliberately synthetic complete display transcript for the fixed batch.
// These literal display amounts/UTC time are independent test expectations;
// they are not generated by the validator and are not emulator evidence.
const approvalLegs = [
  ['AAPL', '0.01 AAPL'], ['NVDA', '0.02 NVDA'], ['MSFT', '0.03 MSFT'], ['USDG', '8 USDG'],
].map(([symbol, amount]) => [
  `Call target | ${fixture.tokens[symbol].address}`, 'Call value (wei) | 0',
  `Contract | ${fixture.tokens[symbol].address}`, 'Native value (wei) | 0',
  `Spender | ${fixture.router}`, `Approval amount | ${amount}`,
]);
const swapLegs = [
  ['AAPL', 'USDG', '0.01 AAPL', '2 USDG'],
  ['NVDA', 'USDG', '0.02 NVDA', '3 USDG'],
  ['MSFT', 'USDG', '0.03 MSFT', '4 USDG'],
  ['USDG', 'AMD', '8 USDG', '0.04 AMD'],
].map(([input, output, amount, minimum]) => [
  `Contract | ${fixture.router}`, `Router caller | ${fixture.implementation}`,
  'Native value (wei) | 0', `Input token | ${fixture.tokens[input].address}`,
  `Output token | ${fixture.tokens[output].address}`, `Input (0=router bal) | ${amount}`,
  `Minimum received | ${minimum}`, 'Pool fee | 0.3 %', `Recipient | ${fixture.wallet}`,
  'Recipient flags | 1=sender; 2=router', 'Sqrt price limit X96 | 0',
]);
const batchScreens = (approvals = approvalLegs, swaps = swapLegs) => [
  'Ethereum | app is ready', 'Interaction with | Rebalance | development',
  `Account | ${fixture.implementation}`, 'Native value (wei) | 0',
  ...approvals.flat(), `Call target | ${fixture.router}`, 'Call value (wei) | 0',
  `Contract | ${fixture.router}`, `Router caller | ${fixture.implementation}`,
  'Native value (wei) | 0', 'Deadline | 2027-01-15 | 08:00:00 AM UTC',
  ...swaps.flat(), 'Network | Robinhood Chain', 'Max fees | 0.000000000001 ETH',
  'Sign transaction',
];

test('actual approval capture has every exact ordered field without asserting a signature', () => {
  const result = check(approvalScreens);
  assert.equal(result.passed, true, JSON.stringify(result.failures));
  assert.equal(result.expectedFieldCount, 6);
  assert.equal(result.matchedFieldCount, 6);
  assert.equal(result.terminalSeen, true);
  assert.equal('signatureCompleted' in result, false);
  assert.equal(check(approvalScreens.map(s => s.toLowerCase().startsWith('spender') ? s.replace(/[A-F]/g, v => v.toLowerCase()) : s)).passed, true);
});

test('approval rejects amount substrings, wrong ticker, truncated or changed spender and nonzero native value', () => {
  for (const wrong of ['18 USDG', '80 USDG', '0.8 USDG', '8 USDG extra', '8 USDT']) {
    const changed = approvalScreens.map(s => s.startsWith('Approval amount') ? `Approval amount | ${wrong}` : s);
    assert.equal(check(changed).passed, false, wrong);
  }
  for (const wrong of [fixture.wallet, fixture.router.slice(0, -1)]) {
    const changed = approvalScreens.map(s => s.startsWith('Spender') ? `Spender | ${wrong}` : s);
    assert.equal(check(changed).passed, false, wrong);
  }
  assert.equal(check(approvalScreens.map(s => s === 'Native value (wei) | 0' ? 'Native value (wei) | 1' : s)).passed, false);
});

test('approval rejects omissions, reordered fields, repeats, unknown screens and absent confirmation', () => {
  assert.equal(check(approvalScreens.filter(s => !s.startsWith('Spender'))).passed, false);
  const reordered = [...approvalScreens];
  [reordered[4], reordered[5]] = [reordered[5], reordered[4]];
  assert.equal(check(reordered).passed, false);
  assert.equal(check([...approvalScreens.slice(0, 6), approvalScreens[5], ...approvalScreens.slice(6)]).passed, false);
  assert.equal(check([...approvalScreens, 'Blind signing']).passed, false);
  assert.equal(check(approvalScreens.slice(0, -1)).passed, false);
  assert.equal(check([...approvalScreens, approvalScreens[5]]).passed, false);
});

test('synthetic batch transcript covers every nested field in exact operation order', () => {
  const result = check(batchScreens(), 'batch');
  assert.equal(result.passed, true, JSON.stringify(result.failures));
  assert.equal(result.expectedFieldCount, 78);
  assert.equal(result.observedFieldCount, 78);
  assert.equal(result.matchedFieldCount, 78);
});

test('batch rejects missing, duplicated or swapped approval and swap calls', () => {
  for (const approvals of [approvalLegs.slice(1), [approvalLegs[0], approvalLegs[0], ...approvalLegs.slice(2)], [approvalLegs[1], approvalLegs[0], ...approvalLegs.slice(2)]]) {
    assert.equal(check(batchScreens(approvals), 'batch').passed, false);
  }
  for (const swaps of [swapLegs.slice(1), [swapLegs[0], swapLegs[0], ...swapLegs.slice(2)], [swapLegs[1], swapLegs[0], ...swapLegs.slice(2)]]) {
    assert.equal(check(batchScreens(approvalLegs, swaps), 'batch').passed, false);
  }
});

test('batch rejects same global amounts assigned to the wrong swap and every altered security field', () => {
  const swappedMinima = swapLegs.map(leg => [...leg]);
  [swappedMinima[0][6], swappedMinima[1][6]] = [swappedMinima[1][6], swappedMinima[0][6]];
  assert.equal(check(batchScreens(approvalLegs, swappedMinima), 'batch').passed, false);
  for (const [prefix, replacement] of [
    ['Call target |', `Call target | ${fixture.wallet}`], ['Call value (wei)', 'Call value (wei) | 1'],
    ['Router caller |', `Router caller | ${fixture.wallet}`], ['Input token |', `Input token | ${fixture.wallet}`],
    ['Output token |', `Output token | ${fixture.wallet}`], ['Recipient |', `Recipient | ${fixture.router}`],
    ['Pool fee |', 'Pool fee | 0.4 %'], ['Sqrt price limit X96 |', 'Sqrt price limit X96 | 1'],
    ['Deadline |', 'Deadline | 2027-01-15 | 08:00:01 AM UTC'], ['Network |', 'Network | Ethereum'],
    ['Max fees |', 'Max fees | 0.000000000002 ETH'],
  ]) {
    const events = batchScreens();
    const index = events.findIndex(s => s.startsWith(prefix));
    assert.notEqual(index, -1);
    events[index] = replacement;
    assert.equal(check(events, 'batch').passed, false, prefix);
  }
});

test('direct swap and router require an independently known expected caller', () => {
  assert.equal(check([], 'swap').passed, false);
  assert.match(check([], 'swap').failures[0].reason, /Router caller/);
  assert.equal(check([], 'router').passed, false);
});

// Actual Nano X direct-swap capture vJ1JaW; public default emulator address.
const capturedSwapScreens = [
  "Ethereum | app is ready",
  "Review transaction to  | Swap exact input",
  "Interaction with | Rebalance  | development",
  "Contract | 0xCaf681a66D020601 | 342297493863E78C95 | 9E5cb2",
  "Router caller | 0xDad77910DbDFdE7 | 64fC21FCD4E74D71b | BACA6D8D",
  "Native value (wei) | 0",
  "Input token | 0xaF3D76f1834A1d4 | 25780943C99Ea8A608 | f8a93f9",
  "Output token | 0x5fc5360D0400a0Fd | 4f2af552ADD042D71 | 6F1d168",
  "Input (0=router bal) | 0.01 AAPL",
  "Minimum received | 2 USDG",
  "Pool fee | 0.3 %",
  "Recipient | 0x11111111111111111 | 1111111111111111111 | 1111",
  "Recipient flags | 1=sender; 2=router",
  "Sqrt price limit X96 | 0",
  "Network | Robinhood Chain",
  "Max fees | 0.000000000001 ETH",
  "Sign transaction"
];
const publicEmulatorAddress = "0xDad77910DbDFdE764fC21FCD4E74D71bBACA6D8D";

test('actual direct swap capture accepts only its exact pre-field review introduction', () => {
  const result = check(capturedSwapScreens, 'swap', publicEmulatorAddress);
  assert.equal(result.passed, true, JSON.stringify(result.failures));
  assert.equal(result.matchedFieldCount, 13);
  const intro = capturedSwapScreens[1];
  assert.equal(check(capturedSwapScreens.map(s => s === intro ? 'Review transaction to | Transfer all tokens' : s), 'swap', publicEmulatorAddress).passed, false);
  assert.equal(check([...capturedSwapScreens.slice(0, 2), intro, ...capturedSwapScreens.slice(2)], 'swap', publicEmulatorAddress).passed, false);
  const late = capturedSwapScreens.filter(s => s !== intro);
  late.splice(4, 0, intro);
  assert.equal(check(late, 'swap', publicEmulatorAddress).passed, false);
  assert.equal(check([intro, ...approvalScreens]).passed, false);
});
